name: xandr

packages:
  - packages/*
  - packages/*/example

sdkPath: .fvm/flutter_sdk

command:
  clean:
    hooks:
      # Runs "flutter clean" in all Flutter packages (`--flutter`)
      # with a concurrency of 3 at a time (`--concurrency=3`).
      post: melos exec --flutter --concurrency=1 -- "fvm flutter clean"
  version:
    # Generate commit links in package changelogs.
    #linkToCommits: true
    # # Only allow versioning to happen on main branch.
    # branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  analyze: fvm flutter analyze .

  pana:
    run: |
      fvm dart run pana . --exit-code-threshold 100 2>&1
    exec:
      concurrency: 1
    packageFilters:
      ignore:
        - "*example*"
    description: Run pana for each package.

  format:
    run: |
      melos format && \
      swiftformat . 2>&1 && \
      ktlint --format '**/*.kt' '**/*.kts' '!**/*.g.kt'
    description: |
      - Requires `swiftformat` (can be installed via Brew on macOS).
      - Requires `ktlint` (can be installed via Brew on macOS).

  test:all:
    run: |
      melos run test --no-select && \
      npx cspell "**/*.md" 2>&1 && \
      melos run merge-trace-files && \
      melos run check-coverage
    description: |
      Run all tests available.

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "fvm flutter test --coverage"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test
      ignore:
        - "*example*"

  merge-trace-files:
    # Merge all packages coverage trace files ignoring data related to generated files.
    description: Merge all packages coverage trace files ignoring data related to generated files.
    run: >
      coverde rm MELOS_ROOT_PATH/coverage/filtered.lcov.info &&
      melos exec --file-exists=coverage/lcov.info -- "coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --paths-parent MELOS_PACKAGE_PATH --filters '\.g\.dart'"

  check-coverage:
    description: Check the coverage of the packages.
    run: >
      coverde check -i MELOS_ROOT_PATH/coverage/filtered.lcov.info 0

  generate:pigeon:
    run: |
      melos exec --concurrency=1 -- "fvm flutter pub run pigeon --input ./pigeons/messages.dart" && \
      melos run format --no-select
    packageFilters:
      fileExists: "pigeons/messages.dart"
    description: Generate the pigeon messages for supported packages.

  generate:pigeon:all:
    run: |
      melos run generate:pigeon --no-select
    description: Generate the pigeon messages for all the supported packages.

  generate:mocks:
    run: |
      melos exec --concurrency=1 -- "fvm flutter pub run build_runner build --delete-conflicting-outputs" && \
      melos run format --no-select
    packageFilters:
      dependsOn:
        - build_runner
    description: Generate mocks for tests.

  generate:mocks:all:
    run: |
      melos run generate:mocks --no-select
    description: Generate mocks for all tests.

  run:example:
    run: fvm flutter run
    description: Run the example app.
    exec:
      concurrency: 1
    packageFilters:
      scope: "xandr_example"

  run:example:interstitial:
    run: fvm flutter run -t lib/main_interstitial.dart
    description: Run the example app showing interstitial ads.
    exec:
      concurrency: 1
    packageFilters:
      scope: "xandr_example"

  run:example:multiadrequest:
    run: fvm flutter run -t lib/main_multi_ad_request.dart
    description: Run the example app loading ads in a multi ad request.
    exec:
      concurrency: 1
    packageFilters:
      scope: "xandr_example"

  run:example:fadeOnDone:
    run: fvm flutter run -t lib/main_fade_on_done.dart
    description: Run the example app fading in once ad loaded.
    exec:
      concurrency: 1
    packageFilters:
      scope: "xandr_example"

  run:example:native:
    run: fvm flutter run -t lib/main_native.dart
    description: Run the example app inclusing just a native ad banner.
    exec:
      concurrency: 1
    packageFilters:
      scope: "xandr_example"
